# Generated by Django 3.2.18 on 2023-03-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230322_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default='1000-01-01T00:00:00Z', verbose_name='Дата публикации'),
        ),
    ]
